app = "fly-xia908-2025"
primary_region = "nrt"

[build]
image = "ghcr.io/eooce/nodejs:main"

[env]
ARGO_AUTH = "eyJhIjoiYTBhNGUxYzQwYjBkYTdkODUyNWQ1MjI1YjllMzg0NDYiLCJ0IjoiZDRiNGJkODAtZGNiNS00YTAyLWJhNGUtNDA1NTYxNTBmYmNmIiwicyI6Ik1qYzJZemxsWW1NdE5XVXpOeTAwT0RKbExUZzRZemt0pBMFpqQXhZekl4TVRsaSJ9"
ARGO_DOMAIN = "fly909.king8888.nyc.mn"
NEZHA_KEY = "P7QOOg71KGhrmVba4FGZ1HxbCyZXrOPq"
NEZHA_SERVER = "nz2.txia393.nyc.mn:80"
UUID = "2215feca-daea-45a6-b548-4dda94ab044f"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 1
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "256mb"